/**
 * Capture registry for the S05 visual historian atlas.
 *
 * Each entry is a durable surface identity. `authority` classifies how the
 * evidence must be collected. Automated entries map to a screenshot basename
 * under docs/design/history/2026-09-s05-complete/screenshots/.
 */

export type CaptureAuthority =
  | 'AUTOMATED-CAPTURE'
  | 'LOCAL-DESKTOP-CAPTURE'
  | 'OWNER-HARDWARE-CAPTURE'
  | 'S06-DEFERRED'

export type SurfaceRole = 'Audience' | 'Host' | 'Shared' | 'App'

export type SurfaceClass = 'normal' | 'edge' | 'recovery' | 'stress'

export interface VisualHistorySurface {
  readonly id: string
  readonly title: string
  readonly role: SurfaceRole
  readonly class: SurfaceClass
  readonly folder: string
  readonly basename: string | null
  readonly authority: CaptureAuthority
  readonly purpose: string
  readonly trigger: string
  readonly components: readonly string[]
  readonly route: string | null
  readonly privacy: 'public' | 'host-private' | 'shared-teacher'
  readonly viewport: '1920x1080' | '1280x720' | 'host-desktop' | 'n/a'
  readonly ownerInspectionRequired: boolean
  readonly notes?: string
}

/**
 * Canonical census for the S05-complete / pre-owner-playthrough milestone.
 * Keep IDs stable; add new milestone archives rather than rewriting history.
 */
export const VISUAL_HISTORY_SURFACES: readonly VisualHistorySurface[] = [
  // ── App / startup ──────────────────────────────────────────────────────────
  {
    id: 'APP-HOME',
    title: 'Home / launch',
    role: 'App',
    class: 'normal',
    folder: 'app',
    basename: 'app-home-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Teacher entry: library, import, open classroom controls',
    trigger: 'Navigate to Home with empty local library',
    components: ['HomeRoute'],
    route: '#/',
    privacy: 'shared-teacher',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'APP-HOME-WITH-GAME',
    title: 'Home after demo import',
    role: 'App',
    class: 'normal',
    folder: 'app',
    basename: 'app-home-with-game-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Game library populated after successful import',
    trigger: 'Import demo game on Home',
    components: ['HomeRoute'],
    route: '#/',
    privacy: 'shared-teacher',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'APP-HOST-EMPTY',
    title: 'Host empty / load a game',
    role: 'Host',
    class: 'normal',
    folder: 'host',
    basename: 'host-empty-load-game.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Host console before a game is loaded',
    trigger: 'Open Host with no active session game',
    components: ['HostRoute', 'GamePackImportPanel'],
    route: '#/host',
    privacy: 'host-private',
    viewport: 'host-desktop',
    ownerInspectionRequired: true,
  },

  // ── Authoring / import ─────────────────────────────────────────────────────
  {
    id: 'AUTH-EDIT-DEMO',
    title: 'Authoring edit after demo import',
    role: 'App',
    class: 'normal',
    folder: 'authoring',
    basename: 'authoring-edit-demo-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'In-app board authoring surface for a saved game',
    trigger: 'Home → Edit on demo game',
    components: ['AuthoringRoute'],
    route: '#/edit/:gameId',
    privacy: 'host-private',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUTH-IMPORT-SUCCESS',
    title: 'Import quality report (success)',
    role: 'App',
    class: 'normal',
    folder: 'authoring',
    basename: 'authoring-import-success-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Teacher-facing import success / quality report',
    trigger: 'Import demo game; quality report visible',
    components: ['HomeRoute', 'ImportQualityReport'],
    route: '#/',
    privacy: 'host-private',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUTH-IMPORT-FAILURE',
    title: 'Import validation failure',
    role: 'App',
    class: 'edge',
    folder: 'authoring',
    basename: null,
    authority: 'LOCAL-DESKTOP-CAPTURE',
    purpose: 'Malformed/unsupported content fail-closed messaging',
    trigger: 'Import intentionally invalid file on Home or Host',
    components: ['HomeRoute', 'GamePackImportPanel'],
    route: '#/',
    privacy: 'host-private',
    viewport: 'n/a',
    ownerInspectionRequired: true,
    notes: 'Requires a prepared invalid fixture file; owner may use Host import panel.',
  },

  // ── Classroom setup ────────────────────────────────────────────────────────
  {
    id: 'SETUP-CLASS-NAMES',
    title: 'Class Setup — team names',
    role: 'Host',
    class: 'normal',
    folder: 'setup',
    basename: 'setup-class-team-names.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Team naming board before play',
    trigger: 'Home import demo → Class Setup names task',
    components: ['ClassroomSetupPanel'],
    route: '#/',
    privacy: 'host-private',
    viewport: 'host-desktop',
    ownerInspectionRequired: true,
  },
  {
    id: 'SETUP-SONY-COPY',
    title: 'Class Setup — Sony ordinary copy',
    role: 'Host',
    class: 'normal',
    folder: 'setup',
    basename: 'setup-sony-ordinary-copy.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Teacher-facing Sony setup copy without WebHID jargon',
    trigger: 'Class Setup visible after demo import',
    components: ['ClassroomSetupPanel'],
    route: '#/',
    privacy: 'host-private',
    viewport: 'host-desktop',
    ownerInspectionRequired: true,
  },
  {
    id: 'SETUP-PHYSICAL-SONY',
    title: 'Sony physical pairing / sleep / wake',
    role: 'Host',
    class: 'edge',
    folder: 'setup',
    basename: null,
    authority: 'OWNER-HARDWARE-CAPTURE',
    purpose: 'Physical controller readiness and recovery',
    trigger: 'Namtai / Sony handsets on owner hardware',
    components: ['ClassroomSetupPanel'],
    route: null,
    privacy: 'host-private',
    viewport: 'n/a',
    ownerInspectionRequired: true,
  },

  // ── Host gameplay ──────────────────────────────────────────────────────────
  {
    id: 'HOST-BOARD-CONTROL',
    title: 'Host category-board control',
    role: 'Host',
    class: 'normal',
    folder: 'host',
    basename: 'host-board-control.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Private board controls with answers withheld from Audience',
    trigger: 'Load board+Final sample; advance to board',
    components: ['CategoryBoardHost', 'HostRoute'],
    route: '#/host',
    privacy: 'host-private',
    viewport: 'host-desktop',
    ownerInspectionRequired: true,
  },
  {
    id: 'HOST-CLUE-SELECTED',
    title: 'Host clue selected / reveal controls',
    role: 'Host',
    class: 'normal',
    folder: 'host',
    basename: 'host-clue-selected.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Host prompt/answer reveal and scoring targets',
    trigger: 'Select a board tile on Host',
    components: ['CategoryBoardHost', 'TeamScoringPanel'],
    route: '#/host',
    privacy: 'host-private',
    viewport: 'host-desktop',
    ownerInspectionRequired: true,
  },
  {
    id: 'HOST-FINAL-SETUP',
    title: 'Host Final setup / begin',
    role: 'Host',
    class: 'normal',
    folder: 'host',
    basename: 'host-final-setup.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Private Final controls before public wager window',
    trigger: 'Advance to Final after board scoring',
    components: ['FinalWagerHostPanel'],
    route: '#/host',
    privacy: 'host-private',
    viewport: 'host-desktop',
    ownerInspectionRequired: true,
  },
  {
    id: 'HOST-FINAL-SETTLEMENT',
    title: 'Host Final settlement controls',
    role: 'Host',
    class: 'normal',
    folder: 'host',
    basename: 'host-final-settlement.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Host adjudication during team reveal',
    trigger: 'Reach Final team-reveal on Host',
    components: ['FinalWagerHostPanel'],
    route: '#/host',
    privacy: 'host-private',
    viewport: 'host-desktop',
    ownerInspectionRequired: true,
  },
  {
    id: 'HOST-ELECTRON-CHROME',
    title: 'Electron Host window chrome',
    role: 'Host',
    class: 'normal',
    folder: 'host',
    basename: null,
    authority: 'LOCAL-DESKTOP-CAPTURE',
    purpose: 'Native window chrome / menu / dual-window shell',
    trigger: 'Packaged or `npm run desktop` Electron Host',
    components: ['desktop main process'],
    route: null,
    privacy: 'host-private',
    viewport: 'n/a',
    ownerInspectionRequired: true,
  },

  // ── Audience board ─────────────────────────────────────────────────────────
  {
    id: 'AUD-BOARD-PRISTINE',
    title: 'Audience pristine board',
    role: 'Audience',
    class: 'normal',
    folder: 'audience',
    basename: 'audience-board-pristine-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Unused category board with eight stress teams',
    trigger: 'Inject visualStressFreshBoardSnapshot',
    components: ['CategoryBoardDisplay', 'AudienceDisplayShell', 'TeamScoreboard'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-BOARD-PARTIAL',
    title: 'Audience partially used board',
    role: 'Audience',
    class: 'normal',
    folder: 'audience',
    basename: 'audience-board-partial-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Used vs unused tiles; long category titles; score extremes',
    trigger: 'Inject visualStressBoardSnapshot',
    components: ['CategoryBoardDisplay', 'TeamScoreboard'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-BOARD-CLEARED-CATEGORY',
    title: 'Audience cleared-category board',
    role: 'Audience',
    class: 'edge',
    folder: 'round-flow',
    basename: 'audience-board-category-cleared-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Durable Cleared label after category depletion',
    trigger: 'Inject visualStressCategoryClearedBoardSnapshot',
    components: ['CategoryBoardDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-BOARD-DEPLETED',
    title: 'Audience nearly/fully depleted board',
    role: 'Audience',
    class: 'edge',
    folder: 'audience',
    basename: 'audience-board-depleted-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'All tiles used; board exhaustion presentation',
    trigger: 'Inject visualHistoryBoardDepletedSnapshot',
    components: ['CategoryBoardDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-BOARD-720P',
    title: 'Audience board at 720p',
    role: 'Audience',
    class: 'stress',
    folder: 'stress',
    basename: 'audience-board-partial-1280x720.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Projector 720p geometry stress for the same partial board',
    trigger: 'Inject visualStressBoardSnapshot at 1280×720',
    components: ['CategoryBoardDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1280x720',
    ownerInspectionRequired: true,
  },

  // ── Clue / buzz / outcome ──────────────────────────────────────────────────
  {
    id: 'AUD-CLUE-SELECTED',
    title: 'Audience clue selected',
    role: 'Audience',
    class: 'normal',
    folder: 'clue',
    basename: 'audience-clue-selected-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Category/value selection before prompt',
    trigger: 'Inject visualStressSelectedSnapshot',
    components: ['CategoryBoardDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-CLUE-PROMPT',
    title: 'Audience prompt (quiet cognition)',
    role: 'Audience',
    class: 'normal',
    folder: 'clue',
    basename: 'audience-clue-prompt-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Prompt revealed without buzz arming',
    trigger: 'Inject visualStressPromptOnlySnapshot',
    components: ['CategoryBoardDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-CLUE-PROMPT-LONG',
    title: 'Audience long-prompt stress',
    role: 'Audience',
    class: 'stress',
    folder: 'stress',
    basename: 'audience-clue-prompt-longtext-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Schema-max prompt readability with timer chrome',
    trigger: 'Inject visualStressLongPromptSnapshot',
    components: ['CategoryBoardDisplay', 'SignalRail'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-CLUE-IMAGE',
    title: 'Audience image clue',
    role: 'Audience',
    class: 'stress',
    folder: 'stress',
    basename: 'audience-clue-image-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Media clue projector balance',
    trigger: 'Inject visualStressImagePromptSnapshot',
    components: ['MediaContentDisplay', 'CategoryBoardDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-CLUE-ANSWER',
    title: 'Audience answer revealed',
    role: 'Audience',
    class: 'normal',
    folder: 'clue',
    basename: 'audience-clue-answer-revealed-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Answer reveal retaining the prompt',
    trigger: 'Inject visualStressAnswerRevealSnapshot',
    components: ['CategoryBoardDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-BUZZ-ARMED',
    title: 'Audience buzz open / waiting',
    role: 'Audience',
    class: 'normal',
    folder: 'buzz',
    basename: 'audience-buzz-armed-waiting-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Response armed with no active claim',
    trigger: 'Inject visualStressArmedWaitingBuzzSnapshot',
    components: ['BuzzQueueDisplay', 'SignalRail'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-BUZZ-ACTIVE',
    title: 'Audience active claim',
    role: 'Audience',
    class: 'normal',
    folder: 'buzz',
    basename: 'audience-buzz-active-claim-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'First active claim identity + waiting count',
    trigger: 'Inject visualStressFirstActiveClaimSnapshot',
    components: ['BuzzQueueDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-BUZZ-MAX-WAITING',
    title: 'Audience active claim max waiting',
    role: 'Audience',
    class: 'stress',
    folder: 'buzz',
    basename: 'audience-buzz-active-max-waiting-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Eight-team waiting count stress',
    trigger: 'Inject visualStressActiveClaimMaxWaitingSnapshot',
    components: ['BuzzQueueDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-OUTCOME-CORRECT',
    title: 'Audience correct outcome',
    role: 'Audience',
    class: 'normal',
    folder: 'outcome',
    basename: 'audience-outcome-correct-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Path A Correct adjudication presentation',
    trigger: 'Inject visualStressBoardCorrectOutcomeSnapshot',
    components: ['BoardOutcomeDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-OUTCOME-INCORRECT',
    title: 'Audience incorrect + promoted claim',
    role: 'Audience',
    class: 'normal',
    folder: 'outcome',
    basename: 'audience-outcome-incorrect-with-active-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Incorrect outcome beside next active claim',
    trigger: 'Inject visualStressBoardIncorrectWithActiveSnapshot',
    components: ['BoardOutcomeDisplay', 'BuzzQueueDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-OUTCOME-PASSED',
    title: 'Audience passed / no-response outcome',
    role: 'Audience',
    class: 'normal',
    folder: 'outcome',
    basename: 'audience-outcome-passed-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Passed adjudication with exhausted queue',
    trigger: 'Inject visualStressBoardPassedOutcomeSnapshot',
    components: ['BoardOutcomeDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },

  // ── Scoreboard / round flow ────────────────────────────────────────────────
  {
    id: 'AUD-SCOREBOARD-STRESS',
    title: 'Audience scoreboard stress (8 teams / negatives)',
    role: 'Audience',
    class: 'stress',
    folder: 'scoreboard',
    basename: 'audience-scoreboard-stress-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Long names, negative and large scores, eight teams',
    trigger: 'Board partial snapshot score strip/column',
    components: ['TeamScoreboard', 'ScoreLayout'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
    notes: 'Same frame as AUD-BOARD-PARTIAL; captured as dedicated crop-intent full frame.',
  },
  {
    id: 'AUD-ROUND-FINAL-BRIDGE',
    title: 'Audience board → Final bridge',
    role: 'Audience',
    class: 'normal',
    folder: 'round-flow',
    basename: 'audience-round-final-bridge-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Display-side transition into Final setup',
    trigger: 'Inject visualStressFinalSetupFromBoardSnapshot',
    components: ['FinalWagerDisplay', 'AudienceDisplayShell'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },

  // ── Final ──────────────────────────────────────────────────────────────────
  {
    id: 'AUD-FINAL-SETUP',
    title: 'Audience Final setup',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-setup-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Neutral Final getting-ready panel',
    trigger: 'Inject visualHistoryFinalSetupSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-WAGER',
    title: 'Audience Final wager phase',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-wager-entry-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Public wager window without wager amounts',
    trigger: 'Inject visualHistoryFinalWagerEntrySnapshot',
    components: ['FinalWagerDisplay', 'SignalRail'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-WAGERS-LOCKED',
    title: 'Audience Final wagers locked',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-wagers-locked-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Locked wager phase in words',
    trigger: 'Inject visualHistoryFinalWagersLockedSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-RESPONSE',
    title: 'Audience Final response phase',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-response-entry-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Question public; answers/responses still private',
    trigger: 'Inject visualHistoryFinalResponseEntrySnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-RESPONSES-LOCKED',
    title: 'Audience Final responses locked',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-responses-locked-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Prompt remains; responses not yet public',
    trigger: 'Inject visualHistoryFinalResponsesLockedSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-ANSWER',
    title: 'Audience Final answer revealed',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-answer-revealed-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Canonical answer beside prompt',
    trigger: 'Inject visualHistoryFinalAnswerRevealedSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-TEAM-PENDING',
    title: 'Audience Final team reveal pending settlement',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-team-reveal-pending-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'One team response/wager public before adjudication',
    trigger: 'Inject visualHistoryFinalTeamRevealPendingSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-SETTLE-CORRECT',
    title: 'Audience Final settlement correct',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-settlement-correct-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Correct settlement wording + signed delta',
    trigger: 'Inject visualHistoryFinalSettlementCorrectSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-SETTLE-INCORRECT',
    title: 'Audience Final settlement incorrect',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-settlement-incorrect-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Incorrect settlement wording + signed delta',
    trigger: 'Inject visualHistoryFinalSettlementIncorrectSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-SETTLE-NO-RESPONSE',
    title: 'Audience Final settlement no-response',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-settlement-no-response-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'No-response settlement wording',
    trigger: 'Inject visualHistoryFinalSettlementNoResponseSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-RESOLUTION-LEADER',
    title: 'Audience Final unique-leader resolution',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-resolution-unique-leader-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Leads / settled state — not winner until complete',
    trigger: 'Inject visualHistoryFinalResolutionUniqueLeaderSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-RESOLUTION-TIED',
    title: 'Audience Final tied resolution',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-resolution-tied-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Tied lead decision state without celebration',
    trigger: 'Inject visualHistoryFinalResolutionTiedSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-FINAL-SUDDEN-DEATH',
    title: 'Audience Final sudden death',
    role: 'Audience',
    class: 'normal',
    folder: 'final',
    basename: 'audience-final-sudden-death-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Neutral sudden-death panel',
    trigger: 'Inject visualHistoryFinalSuddenDeathSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },

  // ── Completion ─────────────────────────────────────────────────────────────
  {
    id: 'AUD-COMPLETE-WINNER',
    title: 'Audience completed unique winner',
    role: 'Audience',
    class: 'normal',
    folder: 'completion',
    basename: 'audience-final-complete-winner-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Winner naming only after explicit game completion',
    trigger: 'Inject visualHistoryFinalCompleteWinnerSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-COMPLETE-TIED',
    title: 'Audience completed tied finish',
    role: 'Audience',
    class: 'normal',
    folder: 'completion',
    basename: 'audience-final-complete-tied-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Tied-finish completion without inventing a winner',
    trigger: 'Inject visualHistoryFinalCompleteTiedSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-COMPLETE-GENERIC',
    title: 'Audience generic safe completion',
    role: 'Audience',
    class: 'recovery',
    folder: 'completion',
    basename: 'audience-final-complete-generic-safe-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Fail closed when unique winner cannot be publicly resolved',
    trigger: 'Inject visualHistoryFinalCompleteGenericSafeSnapshot',
    components: ['FinalWagerDisplay'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },

  // ── Recovery ───────────────────────────────────────────────────────────────
  {
    id: 'AUD-RECOVERY-WAITING',
    title: 'Audience waiting / reconnect',
    role: 'Audience',
    class: 'recovery',
    folder: 'recovery',
    basename: 'audience-recovery-waiting-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Fail-closed Display before valid host publish',
    trigger: 'Open #/display with INITIAL_PUBLIC_STATE',
    components: ['AudienceDisplayShell', 'NexusCore'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-RECOVERY-SCORES-UNAVAILABLE',
    title: 'Audience scores unavailable',
    role: 'Audience',
    class: 'recovery',
    folder: 'recovery',
    basename: 'audience-recovery-scores-unavailable-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Neutral Scores unavailable panel',
    trigger: 'Inject visualHistoryScoresUnavailableSnapshot',
    components: ['ScoreLayout', 'TeamScoreboard'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-RECOVERY-ROUND-UNAVAILABLE',
    title: 'Audience round unavailable',
    role: 'Audience',
    class: 'recovery',
    folder: 'recovery',
    basename: 'audience-recovery-round-unavailable-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Neutral round unavailable fail-closed scene',
    trigger: 'Inject visualHistoryRoundUnavailableSnapshot',
    components: ['AudienceDisplayShell'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-HIGH-CONTRAST',
    title: 'Audience high-contrast theme',
    role: 'Audience',
    class: 'stress',
    folder: 'stress',
    basename: 'audience-board-high-contrast-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'Deterministic high-contrast theme on partial board',
    trigger: 'openDisplay(high-contrast) + visualStressBoardSnapshot',
    components: ['ThemeProvider', 'CategoryBoardDisplay'],
    route: '#/display?theme=high-contrast',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },
  {
    id: 'AUD-REDUCED-MOTION',
    title: 'Audience reduced motion',
    role: 'Audience',
    class: 'stress',
    folder: 'stress',
    basename: 'audience-clue-reduced-motion-1920x1080.png',
    authority: 'AUTOMATED-CAPTURE',
    purpose: 'prefers-reduced-motion presentation on armed clue',
    trigger: 'emulateMedia(reducedMotion) + armed buzz snapshot',
    components: ['CategoryBoardDisplay', 'SignalRail'],
    route: '#/display',
    privacy: 'public',
    viewport: '1920x1080',
    ownerInspectionRequired: true,
  },

  // ── Local desktop / owner hardware / S06 deferred ─────────────────────────
  {
    id: 'DESKTOP-DUAL-WINDOW',
    title: 'Electron Host + Display dual window',
    role: 'Shared',
    class: 'normal',
    folder: 'host',
    basename: null,
    authority: 'LOCAL-DESKTOP-CAPTURE',
    purpose: 'Native dual-window placement on owner desktop',
    trigger: 'Electron shell opens Host + Display windows',
    components: ['desktop main process'],
    route: null,
    privacy: 'shared-teacher',
    viewport: 'n/a',
    ownerInspectionRequired: true,
  },
  {
    id: 'SIDECAR-TWO-SCREEN',
    title: 'MacBook Host + iPad Sidecar Audience',
    role: 'Shared',
    class: 'edge',
    folder: 'host',
    basename: null,
    authority: 'OWNER-HARDWARE-CAPTURE',
    purpose: 'Owner playthrough two-screen Sidecar arrangement',
    trigger: 'Rick Sidecar extended display playthrough',
    components: ['Electron display enumeration'],
    route: null,
    privacy: 'shared-teacher',
    viewport: 'n/a',
    ownerInspectionRequired: true,
    notes: 'Not classroom-projector qualification (S06).',
  },
  {
    id: 'S06-WINDOWS-PROJECTOR',
    title: 'Windows teacher + classroom projector',
    role: 'Shared',
    class: 'edge',
    folder: 'stress',
    basename: null,
    authority: 'S06-DEFERRED',
    purpose: 'Actual classroom projector qualification',
    trigger: 'Authorized S06 hardware qualification',
    components: ['Electron Display window'],
    route: null,
    privacy: 'public',
    viewport: 'n/a',
    ownerInspectionRequired: true,
  },
  {
    id: 'S06-PHYSICAL-CONTROLLERS',
    title: 'Physical Sony controllers in class',
    role: 'Host',
    class: 'edge',
    folder: 'setup',
    basename: null,
    authority: 'S06-DEFERRED',
    purpose: 'Classroom physical controller evidence',
    trigger: 'Authorized S06 hardware qualification',
    components: ['ClassroomSetupPanel', 'input adapters'],
    route: null,
    privacy: 'host-private',
    viewport: 'n/a',
    ownerInspectionRequired: true,
  },
  {
    id: 'S06-SLEEP-WAKE-AUDIO',
    title: 'Sleep/wake, disconnect, classroom audio',
    role: 'Shared',
    class: 'recovery',
    folder: 'recovery',
    basename: null,
    authority: 'S06-DEFERRED',
    purpose: 'Physical recovery and audio qualification',
    trigger: 'Authorized S06 hardware qualification',
    components: ['audio cues', 'display placement'],
    route: null,
    privacy: 'shared-teacher',
    viewport: 'n/a',
    ownerInspectionRequired: true,
  },
]

export function automatedSurfaces(): readonly VisualHistorySurface[] {
  return VISUAL_HISTORY_SURFACES.filter(
    (s) => s.authority === 'AUTOMATED-CAPTURE' && s.basename !== null,
  )
}

export function ownerLocalSurfaces(): readonly VisualHistorySurface[] {
  return VISUAL_HISTORY_SURFACES.filter(
    (s) =>
      s.authority === 'LOCAL-DESKTOP-CAPTURE' || s.authority === 'OWNER-HARDWARE-CAPTURE',
  )
}

export function s06DeferredSurfaces(): readonly VisualHistorySurface[] {
  return VISUAL_HISTORY_SURFACES.filter((s) => s.authority === 'S06-DEFERRED')
}
